apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: NodePort
  selector:
    app: hotel
    department: servicediscovery
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070