apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      app: hotel
      department: servicediscovery
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel
        department: servicediscovery
    spec:
      containers:
        - name: eureka-server
          image: "kamalkk88/eurekaserver:sep28dev"
