apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelmanage-service
spec:
  selector:
    matchLabels:
      app: hotel
      department: hotelmanageservice
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel
        department: hotelmanageservice
    spec:
      containers:
        - name: hotelmanage-service
          image: "kamalkk88/hotelmanageservice:sep28dev"
