apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  selector:
    matchLabels:
      app: hotel
      department: reservationservice
  replicas: 1
  template:
    metadata:
      labels:
        app: hotel
        department: reservationservice
    spec:
      containers:
        - name: reservation-service
          image: "kamalkk88/reservationservice:sep28dev"
